require 'yaml'
require 'thor'
require 'colorize'
require 'deep_merge'
require 'aws-sdk'

require 'cloud_maker/config'
require 'cloud_maker/ec2'
require 'cloud_maker/s3_archiver'
require 'cloud_maker/shell_executor'
